language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
before_install:
  - yes | sdkmanager "platforms;android-30"
script:
  - ./gradlew createOfflineTestCoverageReport
  - ./gradlew jacocoTestCoverageVerification -x test
