language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-27
    - add-on
    - extra
script:
  - ./gradlew createOfflineTestCoverageReport
  - ./gradlew jacocoTestCoverageVerification -x test
