language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
  - ./gradlew createOfflineTestCoverageReport
  - ./gradlew jacocoTestCoverageVerification -x test
