language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
script:
  - ./gradlew createOfflineTestCoverageReport
  - ./gradlew jacocoTestCoverageVerification -x test
