version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: sudo chmod +x ./gradlew
      - run: export TERM=xterm && ./gradlew dependencies
      - run: export TERM=xterm && ./gradlew check
      - run: export TERM=xterm && ./gradlew jacocoTestReport
      - run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN